"""initial schema

Revision ID: 2a48dce27ce4
Revises: 
Create Date: 2025-12-02 15:06:49.412772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a48dce27ce4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('slug', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('location',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('slug', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('location_name', sa.String(length=256), nullable=True),
    sa.Column('menu_categories_order', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('company_slug', sa.String(), nullable=False),
    sa.Column('verified_by_user', sa.Boolean(), nullable=True),
    sa.Column('verified_by_owner', sa.Boolean(), nullable=True),
    sa.Column('reviews_link', sa.String(length=256), nullable=True),
    sa.Column('site', sa.String(length=256), nullable=True),
    sa.Column('subtypes', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('category', sa.String(length=256), nullable=True),
    sa.Column('type', sa.String(length=256), nullable=True),
    sa.Column('company_phone', sa.String(), nullable=True),
    sa.Column('company_phones', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('company_facebook', sa.String(), nullable=True),
    sa.Column('company_instagram', sa.String(), nullable=True),
    sa.Column('email', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('time_zone', sa.String(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('photos_count', sa.Integer(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('price_range', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('reservation_link', sa.String(), nullable=True),
    sa.Column('booking_link', sa.String(), nullable=True),
    sa.Column('order_link', sa.String(), nullable=True),
    sa.Column('location_link', sa.String(), nullable=True),
    sa.Column('place_id', sa.String(), nullable=True),
    sa.Column('google_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_slug'], ['company.slug'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('location_about',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('location_id', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('value', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location_other_hours',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('location_id', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('day_of_week', sa.String(), nullable=True),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location_working_hours',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('location_id', sa.String(), nullable=True),
    sa.Column('day_of_week', sa.String(), nullable=True),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu_category',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('menus_order', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('location_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'location_id', name='uq_menu_category_name_location')
    )
    op.create_table('tag_category',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('menu_category_id', sa.String(), nullable=True),
    sa.Column('item_and_item_categories_order', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('pos_id', sa.Integer(), nullable=True),
    sa.Column('verified_by_user', sa.Boolean(), nullable=True),
    sa.Column('verified_by_owner', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['menu_category_id'], ['menu_category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'location_id', 'menu_category_id', name='uq_menu_name_location_cat')
    )
    op.create_table('tag',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tag_category_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tag_category_id'], ['tag_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_category',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('items_order', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('menu_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'location_id', 'menu_id', name='uq_item_name_loc_menu')
    )
    op.create_table('item',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('full_description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('portion_size', sa.String(), nullable=True),
    sa.Column('cuisine_type', sa.String(), nullable=True),
    sa.Column('preparation_method', sa.String(), nullable=True),
    sa.Column('is_vegan', sa.Boolean(), nullable=True),
    sa.Column('is_vegetarian', sa.Boolean(), nullable=True),
    sa.Column('is_gluten_free', sa.Boolean(), nullable=True),
    sa.Column('is_dairy_free', sa.Boolean(), nullable=True),
    sa.Column('is_nut_free', sa.Boolean(), nullable=True),
    sa.Column('is_low_carb', sa.Boolean(), nullable=True),
    sa.Column('spiciness_level', sa.String(), nullable=True),
    sa.Column('special_notes', sa.Text(), nullable=True),
    sa.Column('calories', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('proteins', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('carbs', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fat', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fiber', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sugar', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sodium', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('item_category_id', sa.String(), nullable=True),
    sa.Column('menu_id', sa.String(), nullable=True),
    sa.Column('location_id', sa.String(), nullable=True),
    sa.Column('option_groups_order', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('pos_id', sa.Integer(), nullable=True),
    sa.Column('background_information', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_category_id'], ['item_category.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'location_id', 'menu_id', name='uq_item_cat_name_loc_menu')
    )
    op.create_table('allergens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('item_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingredients')
    op.drop_table('allergens')
    op.drop_table('item')
    op.drop_table('item_category')
    op.drop_table('tag')
    op.drop_table('menu')
    op.drop_table('tag_category')
    op.drop_table('menu_category')
    op.drop_table('location_working_hours')
    op.drop_table('location_other_hours')
    op.drop_table('location_about')
    op.drop_table('location')
    op.drop_table('company')
    # ### end Alembic commands ###
